from sqlalchemy import URL, create_engine, text
from app.env_settings import Settings

settings = Settings()


def connection(settings):
    url_object = URL.create(
        "postgresql+psycopg",
        username=settings.db_username,
        password=settings.db_password,
        host="postgres-db",
        port=settings.db_port,
        database=settings.db_name
    )

    engine = create_engine(
        url_object,
        connect_args={"connect_timeout": 3}
        )

    return engine

def create_table(name, engine):
    with engine.connect() as conn:
        result = conn.execute(text(f"""CREATE TABLE IF NOT EXISTS {name} (
                                    "Prediction ID" INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                    "Sample ID" INTEGER,
                                    "Raw Prediction" FLOAT,
                                    "Uncertainty" FLOAT,
                                    "Predicted Label" TEXT,
                                    "True Label" TEXT,
                                    "MC Dropout Passes" INTEGER
                                    )"""
                                    ))
        conn.commit()

def add_item(name, engine, ID, RP, U, PL, TL, T):
    with engine.connect() as conn:
        result = conn.execute(
            text(f"""INSERT INTO {name} ("Sample ID", "Raw Prediction", "Uncertainty", "Predicted Label", "True Label", "MC Dropout Passes")
                     VALUES (:ID, :RP, :U, :PL, :TL, :T)"""),
            {
                "ID": ID,
                "RP": RP,
                "U": U,
                "PL": PL,
                "TL": TL,
                "T": T
            }
        )
        conn.commit()





